//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trials
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public int RunId { get; set; }
        public Nullable<int> Faults { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<int> TrackID { get; set; }
    
        public virtual Track Track { get; set; }
    }
}
